# Generated by Django 3.2.5 on 2021-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('product_id', models.CharField(max_length=90)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tblcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=90)),
                ('product_id', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('complaint', models.CharField(max_length=200)),
                ('complaint_date', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tblcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tbllogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tblorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('product_id', models.CharField(max_length=90)),
                ('order_qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_date', models.CharField(max_length=90)),
                ('order_status', models.CharField(max_length=90)),
                ('payment_mode', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tblpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(max_length=90)),
                ('order_id', models.CharField(max_length=90)),
                ('card_no', models.CharField(max_length=90)),
                ('cvv', models.CharField(max_length=90)),
                ('mobile_no', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('tran_date', models.CharField(max_length=90)),
                ('time', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='tblproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=80)),
                ('product_name', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
                ('unit_price', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('photo', models.CharField(max_length=90)),
                ('size', models.IntegerField()),
                ('colour', models.CharField(max_length=90)),
                ('age_group', models.CharField(max_length=80)),
                ('remark', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tblreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=90)),
                ('product_id', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('review', models.CharField(max_length=200)),
                ('review_date', models.CharField(max_length=90)),
            ],
        ),
    ]
