# Generated by Django 3.2.5 on 2021-10-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddies_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='mobile_no',
            field=models.CharField(max_length=90),
        ),
    ]
