# Generated by Django 3.2.5 on 2021-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddies_app', '0002_auto_20211025_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblorder_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details_id', models.CharField(max_length=90)),
                ('cust_id', models.CharField(max_length=90)),
                ('product_id', models.CharField(max_length=90)),
                ('quantity', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
                ('price', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('order_no', models.CharField(max_length=90)),
            ],
        ),
    ]
