# Generated by Django 3.1.1 on 2021-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddies_app', '0006_auto_20211027_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblorder',
            name='amount',
            field=models.CharField(max_length=90),
        ),
    ]
