# Generated by Django 3.2.5 on 2021-10-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiddies_app', '0009_auto_20211027_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpayment',
            old_name='order_id',
            new_name='order_no',
        ),
    ]
